rm ./utils/__pycache__/write_results.cpython-36.pyc
rm ./utils/__pycache__/DispMap.cpython-36.pyc
rm ./utils/__pycache__/custom_loss.cpython-36.pyc
rm ./utils/__pycache__/misc.cpython-36.pyc
rm ./utils/__pycache__/get_parser.cpython-36.pyc
rm ./tasks/__pycache__/common.cpython-36.pyc
rm ./tasks/__pycache__/test.cpython-36.pyc
rm ./networks/__pycache__/pool_model.cpython-36.pyc
rm ./networks/__pycache__/bam.cpython-36.pyc
rm ./networks/__pycache__/cbam.cpython-36.pyc
rm ./networks/__pycache__/get_model.cpython-36.pyc
rm ./networks/__pycache__/deattention_model.cpython-36.pyc
rm ./networks/__pycache__/Segmentation.cpython-36.pyc
rm ./networks/__pycache__/netvlad.cpython-36.pyc
rm ./networks/__pycache__/senet.cpython-36.pyc
rm ./networks/MobileNet/__pycache__/_deeplab.cpython-36.pyc
rm ./networks/MobileNet/__pycache__/__init__.cpython-36.pyc
rm ./networks/MobileNet/__pycache__/modeling.cpython-36.pyc
rm ./networks/MobileNet/__pycache__/utils.cpython-36.pyc
rm ./networks/MobileNet/__pycache__/cityscapes.cpython-36.pyc
rm ./networks/MobileNet/backbone/__pycache__/mobilenetv2.cpython-36.pyc
rm ./networks/MobileNet/backbone/__pycache__/resnet.cpython-36.pyc
rm ./networks/MobileNet/backbone/__pycache__/__init__.cpython-36.pyc
rm ./dataloaders/__pycache__/pittsburgh.cpython-36.pyc
rm ./dataloaders/__pycache__/tokyo247.cpython-36.pyc
rm ./dataloaders/__pycache__/tokyoTM.cpython-36.pyc
